version: 2

general:
  branches:
    only:
      - bazel

# Empty config on the master branch.
# The bazel branch has an actual set of jobs to run
workflows:
  version: 2
  default_workflow:
    jobs:
