version: 2

general:
  branches:
    only:
      - bazel

jobs:
  build:
    steps:
      - echo "no-op build"
  lint:
    steps:
      - echo "no-op lint"

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - lint
