version: 2

general:
  branches:
    only:
      - bazel

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "no-op build"

workflows:
  version: 2
  default_workflow:
    jobs:
      - build